#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         eSTAR-RTML
version:      1.8.0
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
